image: docker:latest
services:
  - docker:dind

stages:
  - build
  - docker
  - docker-release
  - deploy-sandbox
  - deploy-fallback
  - deploy-live

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  AUDIT_REGISTRY_IMAGE: ebispot/gwas-deposition-audit
  AUDIT_SERVICE_NAME: gwas-deposition-audit

maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - echo ${MAVEN_SETTINGS} | base64 -d > settings.xml
    - mvn -s settings.xml clean install -B -Dspring.profiles.active=test
  artifacts:
    paths:
      - target/*.jar

build-ingest-container:
  stage: docker
  script:
  - echo "$DOCKER_HUB_PASSWORD" > dhpw.txt
  - docker login -u "${DOCKER_HUB_USER}" --password-stdin < dhpw.txt
  - docker build --cache-from $AUDIT_REGISTRY_IMAGE:latest -t $AUDIT_REGISTRY_IMAGE:$CI_COMMIT_SHA .
  - docker push $AUDIT_REGISTRY_IMAGE:$CI_COMMIT_SHA

build-ingest-release:
  variables:
    GIT_STRATEGY: none
  stage: docker-release
  script:
  - echo "$DOCKER_HUB_PASSWORD" > dhpw.txt
  - docker login -u "${DOCKER_HUB_USER}" --password-stdin < dhpw.txt
  - docker pull $AUDIT_REGISTRY_IMAGE:$CI_COMMIT_SHA
  - docker tag $AUDIT_REGISTRY_IMAGE:$CI_COMMIT_SHA $AUDIT_REGISTRY_IMAGE:latest
  - docker tag $AUDIT_REGISTRY_IMAGE:$CI_COMMIT_SHA $AUDIT_REGISTRY_IMAGE:$CI_COMMIT_TAG
  - docker push $AUDIT_REGISTRY_IMAGE:latest
  - docker push $AUDIT_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
  - tags

deploy-ingest-sandbox:
  image: dtzar/helm-kubectl:2.13.1
  stage: deploy-sandbox
  script:
  - echo "Deploy to sandbox server"
  - mkdir -p /root/.kube
  - echo ${SANBOX_KUBECONF} | base64 -d > /root/.kube/config
  - helm init
  - helm delete --purge gwas-audit-service || true
  - helm install --name gwas-audit-service --set k8Namespace=gwas,image.repository=$AUDIT_REGISTRY_IMAGE,image.tag=$CI_COMMIT_SHA,image.env.secretsName=sandbox-secrets,image.env.secretsKey=db-backend ./k8chart/ --wait
  environment:
    name: sandbox
  only:
  - develop

deploy-fallback:
  image: dtzar/helm-kubectl:2.13.1
  stage: deploy-fallback
  script:
  - echo "Deploy to Production fallback server"
  - mkdir -p /root/.kube
  - echo ${PFALLBACK_KUBECONFIG} | base64 -d > /root/.kube/config
  - helm init
  - helm delete --purge gwas-audit-service || true
  - helm install --name gwas-audit-service --set k8Namespace=gwas,image.env.envName=prod,image.repository=$AUDIT_REGISTRY_IMAGE,image.tag=$CI_COMMIT_SHA,image.env.dbUser=gwasdepo,image.env.secretsName=prod-secrets,image.env.secretsKey=db-backend ./k8chart/ --wait
  environment:
    name: prod
  only:
  - tags

deploy-live:
  image: dtzar/helm-kubectl:2.13.1
  stage: deploy-live
  script:
  - echo "Deploy to Production server"
  - mkdir -p /root/.kube
  - echo ${PLIVE_KUBECONFIG} | base64 -d > /root/.kube/config
  - helm init
  - helm delete --purge gwas-audit-service || true
  - helm install --name gwas-audit-service --set k8Namespace=gwas,image.env.envName=prod,image.repository=$AUDIT_REGISTRY_IMAGE,image.tag=$CI_COMMIT_SHA,image.env.dbUser=gwasdepo,image.env.secretsName=prod-secrets,image.env.secretsKey=db-backend ./k8chart/ --wait
  environment:
    name: prod
  only:
  - tags
