server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongo-0.mongo.gwas-dev.svc.cluster.local,mongo-1.mongo.gwas-dev.svc.cluster.local,mongo-2.mongo.gwas-dev.svc.cluster.local:27017
  mail:
    host: outgoing.ebi.ac.uk
    port: 587
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: false
          sendpartial: true
          starttls:
            enable: true

audit-emails:
  active: true
  digest:
    to: jstewart@ebi.ac.uk
  urls:
    base: http://193.62.54.159

email:
  enabled: true

gwas-audit-service:
  db: deposition-backend-sandbox

quartz:
  scheduler:
    dbName: deposition-backend-sandbox
