#===============COMPULSORY PROGRAM ARGUMENTS=====#
mongo-server:
auth-enable:
solr-server:
#===============COMPULSORY PROGRAM ARGUMENTS=====#

server:
  port: 8085

logging:
  level:
    org:
      springframework: DEBUG

spring:
  data:
    mongodb:
      uri: ${mongo-server}

gwas-audit-service:
  auth:
    enabled: false
  db: gwasdepo

quartz:
  scheduler:
    dbName: gwasdepo



rabbitmq:
  queue-name: study_change_sandbox
  exchange-name: study_change_exchange_sandbox
  routing-key: study-ingest_sandbox
  sumstats:
    queue-name: metadata-yml-update-sandbox
    exchange-name: metadata-yml-update-exchange-sandbox
    routing-key: metadata-yml-update-route-sandbox