spring:
  data:
    mongodb:
      uri: snoopy.ebi.ac.uk:27017

gwas-audit-service:
  db: gwas-deposition-test

quartz:
  scheduler:
    dbName: gwas-deposition-test

audit-emails:
  active: true
  digest:
    subject: New submissions report
    content: emails/digest.email
    to: gwas-curator@ebi.ac.uk, gwas-dev-logs@ebi.ac.uk
