server:
  name: deposition-audit-service
  port: 80

logging:
  level:
    org:
      springframework:
        web: DEBUG

gwas-audit-service:
  auth:
    enabled: false

quartz:
  scheduler:
    active: true
    instanceName: auditSchedulerJobSchedulerCluster
    environment-config: quartz/environment-config.yaml
    mongodb-pool-size: 10
  jobs:
    daily-stats:
      schedule: 0 0 8 * * ?

spring:
  profiles:
    active: dev

comms:
  messaging:
    enabled: false
