server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb-hx-gwasdepopro-001.ebi.ac.uk:27017,mongodb-hl-gwasdepopro-002.ebi.ac.uk:27017/admin?replicaSet=gwasdepoprors080
  mail:
    host: hx-smtp.ebi.ac.uk
    port: 25
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: false
          sendpartial: true
          starttls:
            enable: true

audit-emails:
  active: true

email:
  enabled: true

gwas-audit-service:
  db: gwasdepo

quartz:
  scheduler:
    dbName: gwasdepo

rabbitmq:
  queue-name: study_change
  exchange-name: study_change_exchange
  routing-key: study-ingest
  sumstats:
    queue-name: metadata-yml-update
    exchange-name: metadata-yml-update-exchange
    routing-key: metadata-yml-update-route